# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAnnounce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
