# Generated by Django 3.1.2 on 2020-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_serviceannounce_email_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceannounce',
            name='email_to',
            field=models.CharField(choices=[('lnl@wpi.edu', 'Exec Board'), ('lnl-active@wpi.edu', 'Active Members'), ('lnl-news@wpi.edu', 'LNL News'), ('lnl-w@wpi.edu', 'Webmaster')], default='lnl@wpi.edu', max_length=24),
        ),
    ]
