# Generated by Django 3.1.8 on 2021-04-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20201028_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceAnnounce',
        ),
    ]
