# Generated by Django 3.1.8 on 2021-06-21 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehour',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='events.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officehour',
            name='hour_end',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='hour_start',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
