# Generated by Django 3.1.8 on 2021-06-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_officehour_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HourChange',
        ),
    ]
