# Generated by Django 3.1.8 on 2021-06-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_hourchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='billing_fund',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='accounts',
        ),
        migrations.AddField(
            model_name='organization',
            name='workday_fund',
            field=models.IntegerField(blank=True, choices=[(810, 'Student Organization (810-FD)'), (110, 'Operating (110-FD)'), (220, 'Gift (220-FD)'), (250, 'Gift (250-FD)'), (500, 'Gift (500-FD)'), (210, 'Grant (210-FD)'), (900, 'Project (900-FD)'), (120, 'Designated (120-FD)')], null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='worktag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
