# Generated by Django 3.1.8 on 2021-10-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event2019',
            name='send_survey',
            field=models.BooleanField(default=True, help_text='Check if the event contact should be emailed the post-event survey after the event'),
        ),
    ]
