# Generated by Django 3.1.13 on 2021-10-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211025_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='event2019',
            name='allow_crew_to_check_equipment',
            field=models.BooleanField(default=False, help_text='Allow checked-in crew to check in or out equipment on the Pull List.'),
        ),
    ]
