# Generated by Django 3.1.8 on 2022-02-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20211110_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewattendancerecord',
            options={},
        ),
    ]
