# Generated by Django 3.1.13 on 2021-10-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20211029_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event2019',
            name='allow_crew_to_check_equipment',
            field=models.BooleanField(default=True, help_text='Allow checked-in crew to check in or out equipment on the Pull List.'),
        ),
    ]
