# Generated by Django 3.1.14 on 2023-08-27 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_auto_20220210_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='lnl_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lnl_contact', to=settings.AUTH_USER_MODEL, verbose_name='LNL Contact'),
        ),
    ]
