# Generated by Django 3.1.14 on 2023-09-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20230827_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseevent',
            options={'ordering': ['-datetime_start'], 'permissions': (('view_events', "Show an event that isn't hidden"), ('add_raw_event', 'Use the editor to create an event'), ('event_images', 'Upload images to an event'), ('view_hidden_event', 'Show hidden events'), ('cancel_event', 'Declare an event to be cancelled'), ('event_attachments', 'Upload attachments to an event'), ('edit_event_times', 'Modify the dates for an event'), ('add_event_report', 'Add reports about the event'), ('edit_event_fund', 'Change where money for an event comes from'), ('view_event_billing', 'See financial info for event'), ('view_event_reports', 'See reports for event'), ('edit_event_text', 'Update any event descriptions'), ('edit_event_status', 'Change the status for an event'), ('adjust_event_owner', 'Change the event contact and organization'), ('edit_event_hours', 'Modify the time sheets'), ('edit_event_flags', 'Add flags to an event'), ('edit_event_lnl_contact', 'Change the LNL contact for an event'), ('event_view_sensitive', 'Show internal notes and other metadata marked as not public'), ('approve_event', 'Accept an event'), ('decline_event', 'Decline an event'), ('can_chief_event', 'Can crew chief an event'), ('review_event', 'Review an event for billing'), ('adjust_event_charges', 'Add charges and change event type'), ('bill_event', 'Send bills and mark event paid'), ('close_event', 'Lock an event after everything is done.'), ('view_test_event', 'Show events for testing'), ('event_view_granular', 'See debug data like ip addresses'), ('event_view_debug', 'See debug events'), ('reopen_event', 'Reopen a closed, declined, or cancelled event')), 'verbose_name': 'Event'},
        ),
        migrations.AddField(
            model_name='baseevent',
            name='event_status',
            field=models.CharField(choices=[('Pre', 'Pre-Request'), ('Pro', 'Prospective'), ('I', 'Incoming'), ('C', 'Confirmed'), ('Post', 'Post Event')], default='Pro', max_length=20),
        ),
    ]
