# Generated by Django 4.2.13 on 2024-12-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0012_auto_20230905_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='associated_orgs',
            field=models.ManyToManyField(blank=True, to='events.organization', verbose_name='Associated Clients'),
        ),
    ]
