# Generated by Django 4.2.13 on 2025-01-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0005_channel_allowed_groups_channel_required_groups"),
        ("events", "0013_alter_baseevent_polymorphic_ctype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseevent",
            name="slack_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event",
                to="slack.channel",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="slack_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization",
                to="slack.channel",
            ),
        ),
    ]
