# Generated by Django 4.2.13 on 2025-06-30 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_baseevent_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.pricelist')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.service')),
            ],
        ),
        migrations.AddField(
            model_name='pricelist',
            name='services',
            field=models.ManyToManyField(related_name='pricelists', through='events.ServicePrice', to='events.service'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='pricelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.pricelist'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.UniqueConstraint(fields=('service', 'pricelist'), name='unique_service_pricelist'),
        ),
    ]
