# Generated by Django 4.2.13 on 2025-06-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_baseevent_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.baseevent')),
            ],
        ),
    ]
