# Generated by Django 4.2.13 on 2026-02-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'ordering': ('event',)},
        ),
    ]
