# Generated by Django 4.2.13 on 2025-10-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'ordering': ('event',)},
        ),
        migrations.AddField(
            model_name='eventccinstance',
            name='position',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
