# Generated by Django 4.2.13 on 2025-01-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0005_channel_allowed_groups_channel_required_groups"),
        ("events", "0014_baseevent_slack_channel_organization_slack_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseevent",
            name="notifications_in_slack_channel",
            field=models.BooleanField(
                default=True,
                help_text="Check to send event edited notifications to the event slack channel",
                verbose_name="Send edit notifications to Slack channel",
            ),
        ),
        migrations.AlterField(
            model_name="baseevent",
            name="slack_channel",
            field=models.ForeignKey(
                blank=True,
                help_text="Slack Channel ID, i.e. C4HB02R6H",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event",
                to="slack.channel",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slack_channel",
            field=models.ForeignKey(
                blank=True,
                help_text="Slack Channel ID, i.e. C4HB02R6H",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization",
                to="slack.channel",
            ),
        ),
    ]
