# Generated by Django 4.2.13 on 2026-03-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_hours_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='is_default_pricelist',
            field=models.BooleanField(default=False),
        ),
    ]
