# Generated by Django 4.2.13 on 2025-10-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_cc_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventccinstance',
            name='position',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='eventccinstance',
            name='setup_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ccinstances', to='events.location'),
        ),
    ]
