# Generated by Django 4.2.13 on 2026-06-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("events", "0017_is_sga_funded"), ("events", "0018_is_sga_funded")]

    dependencies = [
        ("events", "0016_pricelist_default_pricelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="event2019",
            name="is_sga_funded",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not this event is fully funded by SGA and the client should be charged $0.",
                verbose_name="Is SGA-funded",
            ),
        ),
    ]
