# Generated by Django 4.2.13 on 2026-07-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_cc_position"),
        ("events", "0016_pricelist_default_pricelist"),
    ]

    operations = []
