# Generated by Django 4.2.13 on 2026-07-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_merge_20260702_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventccinstance",
            name="position_is_bold",
            field=models.BooleanField(default=False),
        ),
    ]
