# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-15 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_add_service_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event2019',
            name='entered_into_workday',
            field=models.BooleanField(default=False, help_text=b'Checked when the Treasurer has created an Internal Service Delivery in Workday for this event'),
        ),
        migrations.AddField(
            model_name='event2019',
            name='workday_form_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event2019',
            name='workday_fund',
            field=models.IntegerField(blank=True, choices=[(810, b'Student Organization (810-FD)'), (110, b'Operating (110-FD)'), (220, b'Gift (220-FD)'), (500, b'Gift (500-FD)'), (210, b'Grant (210-FD)'), (900, b'Project (900-FD)'), (120, b'Designated (120-FD)')], null=True),
        ),
        migrations.AddField(
            model_name='event2019',
            name='worktag',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
