# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-30 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0024_rename_billed_by_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='event2019',
            name='workday_entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workdayentries', to=settings.AUTH_USER_MODEL),
        ),
    ]
