# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event2019_workday_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event2019',
            name='workday_fund',
            field=models.IntegerField(blank=True, choices=[(810, b'Student Organization (810-FD)'), (110, b'Operating (110-FD)'), (220, b'Gift (220-FD)'), (250, b'Gift (250-FD)'), (500, b'Gift (500-FD)'), (210, b'Grant (210-FD)'), (900, b'Project (900-FD)'), (120, b'Designated (120-FD)')], null=True),
        ),
        migrations.AlterField(
            model_name='event2019',
            name='worktag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
