# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-26 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_posteventsurvey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteventsurvey',
            name='crew_knowledgeability',
        ),
        migrations.RemoveField(
            model_name='posteventsurvey',
            name='crew_preparedness',
        ),
        migrations.RemoveField(
            model_name='posteventsurvey',
            name='quote_as_expected',
        ),
        migrations.AddField(
            model_name='posteventsurvey',
            name='work_order_ease',
            field=models.IntegerField(blank=True, choices=[(0, b'Poor'), (1, b'Fair'), (2, b'Good'), (3, b'Very good'), (4, b'Excellent'), (-1, b'Not applicable')], default=-1, null=True, verbose_name=b"How would you rate the workorder tool's clarity and ease of use?"),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='comments',
            field=models.TextField(blank=True, verbose_name=b'Please use this area to provide any other feedback you may have about your event.'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='communication_responsiveness',
            field=models.IntegerField(choices=[(0, b'Strongly disagree'), (1, b'Disagree'), (2, b'Neither agree nor disagree'), (3, b'Agree'), (4, b'Strongly agree'), (-1, b'Not applicable')], verbose_name=b'Lens and Lights was responsive to my communications.'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='crew_respectfulness',
            field=models.IntegerField(choices=[(0, b'Strongly disagree'), (1, b'Disagree'), (2, b'Neither agree nor disagree'), (3, b'Agree'), (4, b'Strongly agree'), (-1, b'Not applicable')], verbose_name=b'When interacting with the crew they were helpful and respectful.'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='customer_would_return',
            field=models.IntegerField(choices=[(0, b'Strongly disagree'), (1, b'Disagree'), (2, b'Neither agree nor disagree'), (3, b'Agree'), (4, b'Strongly agree'), (-1, b'Not applicable')], verbose_name=b'I would use Lens and Lights in the future.'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='lighting_quality',
            field=models.IntegerField(choices=[(0, b'Poor'), (1, b'Fair'), (2, b'Good'), (3, b'Very good'), (4, b'Excellent'), (-1, b'Not applicable')], verbose_name=b'How satisfied were you with the lighting?'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='price_appropriate',
            field=models.IntegerField(choices=[(0, b'Strongly disagree'), (1, b'Disagree'), (2, b'Neither agree nor disagree'), (3, b'Agree'), (4, b'Strongly agree'), (-1, b'Not applicable')], verbose_name=b'The price quoted for the event matched my expectations and was appropriate for the services provided.'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='pricelist_ux',
            field=models.IntegerField(choices=[(0, b'Strongly disagree'), (1, b'Disagree'), (2, b'Neither agree nor disagree'), (3, b'Agree'), (4, b'Strongly agree'), (-1, b'Not applicable')], verbose_name=b'It was easy to determine which services to request.'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='services_quality',
            field=models.IntegerField(choices=[(0, b'Poor'), (1, b'Fair'), (2, b'Good'), (3, b'Very good'), (4, b'Excellent'), (-1, b'Not applicable')], verbose_name=b'Please rate the overall quality of the services Lens and Lights provided.'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='setup_on_time',
            field=models.IntegerField(choices=[(0, b'Strongly disagree'), (1, b'Disagree'), (2, b'Neither agree nor disagree'), (3, b'Agree'), (4, b'Strongly agree'), (-1, b'Not applicable')], verbose_name=b'My event was set up and the crew was ready on time.'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='sound_quality',
            field=models.IntegerField(choices=[(0, b'Poor'), (1, b'Fair'), (2, b'Good'), (3, b'Very good'), (4, b'Excellent'), (-1, b'Not applicable')], verbose_name=b'How satisfied were you with the sound system?'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='work_order_experience',
            field=models.IntegerField(blank=True, choices=[(0, b'Poor'), (1, b'Fair'), (2, b'Good'), (3, b'Very good'), (4, b'Excellent'), (-1, b'Not applicable')], default=-1, null=True, verbose_name=b'How would you rate your overall experience using the work order tool?'),
        ),
        migrations.AlterField(
            model_name='posteventsurvey',
            name='work_order_method',
            field=models.IntegerField(choices=[(None, b'Please select...'), (1, b'Via the website at lnl.wpi.edu/workorder'), (2, b'Emailed lnl@wpi.edu'), (3, b'Emailed an LNL representative directly'), (4, b'By phone'), (5, b'In person'), (0, b'Other'), (-1, b"I don't know")], verbose_name=b'How did you submit the work order?'),
        ),
    ]
