# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_workshop_workshopdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdate',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.Workshop'),
        ),
    ]
