# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_hour_hourchange'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hour',
            new_name='OfficeHour',
        ),
    ]
