# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20200330_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'permissions': (('edit_workshops', 'Modify workshops'),)},
        ),
    ]
