# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-09 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0035_auto_20200628_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewAttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_attendance', to='events.Event2019')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_attendance_records', 'View Attendance Records'),),
            },
        ),
    ]
