# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-09 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_crewattendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='event2019',
            name='max_crew',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
