# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'permissions': (('view_laptop_details', 'View details of a laptop'), ('view_laptop_history', 'View password retrieval history for a laptop'), ('retrieve_user_password', 'Retrieve the user password for a laptop'), ('retrieve_admin_password', 'Retrieve the admin password for a laptop'), ('manage_mdm', 'Enroll and/or manage devices through the MDM'))},
        ),
        migrations.AddField(
            model_name='laptop',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='last_ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Last Network IP Address'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='mdm_enrolled',
            field=models.BooleanField(default=False, verbose_name='Enrolled in MDM'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='serial',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='api_key_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hash of the API key that the laptop uses to communicate with the database', max_length=64, verbose_name='API key hash'),
        ),
    ]
