# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200608_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.FilePathField(match='.*\\.json$', path='/isihome/lnl/public_html/media/profiles/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_modified'],
                'permissions': (('view_removal_password', 'Retrieve the removal password for a profile'),)
            },
        ),
        migrations.AlterField(
            model_name='laptop',
            name='admin_password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='user_password',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='configurationprofile',
            name='installed',
            field=models.ManyToManyField(blank=True, related_name='installed', to='devices.Laptop'),
        ),
        migrations.AddField(
            model_name='configurationprofile',
            name='pending_install',
            field=models.ManyToManyField(blank=True, related_name='pending', to='devices.Laptop'),
        ),
    ]
