# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_configurationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=36, null=True)),
                ('installed_on', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_records', to='devices.Laptop')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install_records', to='devices.ConfigurationProfile')),
            ],
        ),
    ]
