# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_installationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationprofile',
            name='scope',
            field=models.CharField(choices=[('System', 'System'), ('User', 'User')], default='System', max_length=6),
        ),
    ]
