# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_macosapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationrecord',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install_records', to='devices.MacOSApp'),
        ),
    ]
