# Generated by Django 3.1.2 on 2020-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20200827_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationprofile',
            name='profile',
            field=models.FilePathField(match='.*\\.json$', path='/home/lnl/public_html/media/profiles'),
        ),
    ]
