# Generated by Django 3.1.2 on 2020-10-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20201028_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'permissions': (('view_laptop_history', 'View password retrieval history for a laptop'), ('retrieve_user_password', 'Retrieve the user password for a laptop'), ('retrieve_admin_password', 'Retrieve the admin password for a laptop'), ('manage_mdm', 'Enroll and/or manage devices through the MDM'))},
        ),
    ]
