# Generated by Django 3.1.8 on 2021-11-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20201028_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macosapp',
            name='update_available',
        ),
        migrations.AddField(
            model_name='macosapp',
            name='developer_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macosapp',
            name='managed',
            field=models.BooleanField(default=False, verbose_name='Available in MSC'),
        ),
        migrations.AddField(
            model_name='macosapp',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.macosapp', verbose_name='mergedapps'),
        ),
        migrations.AddField(
            model_name='macosapp',
            name='requires_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='macosapp',
            name='identifier',
            field=models.CharField(blank=True, help_text='Homebrew Identifier', max_length=64, null=True),
        ),
    ]
