# Generated by Django 3.1.13 on 2021-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20211110_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationprofile',
            name='profile',
            field=models.FilePathField(match='.*\\.json$', path='/Users/benjamin/Documents/GitHub/lnldb-muirrum/runtime/media/profiles'),
        ),
    ]
