# Generated by Django 3.1.14 on 2023-09-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20211110_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationprofile',
            name='profile',
            field=models.FilePathField(match='.*\\.json$', path='/home/pfrunzio/lnl/lnldb/runtime/media/profiles'),
        ),
    ]
