# Generated by Django 4.2.13 on 2026-02-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20230905_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationprofile',
            name='profile',
            field=models.FilePathField(match='.*\\.json$', path='/root/lnldb/runtime/media/profiles'),
        ),
    ]
