# Generated by Django 3.1.8 on 2022-02-24 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20220204_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepting_requests', models.BooleanField(default=True)),
                ('allow_explicit', models.BooleanField(default=True)),
                ('auto_approve', models.BooleanField(default=False)),
                ('require_payment', models.BooleanField(default=False)),
                ('allow_silence', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('paypal', models.URLField(blank=True, help_text='PayPal.Me Link', null=True)),
                ('venmo', models.CharField(blank=True, help_text='Venmo username', max_length=16, null=True)),
                ('venmo_verification', models.CharField(blank=True, max_length=4, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event2019')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('spotify_id', models.CharField(blank=True, max_length=150, null=True)),
                ('token_info', jsonfield.fields.JSONField(blank=True, null=True)),
                ('personal', models.BooleanField(default=True, help_text='Uncheck this for shared club accounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('identifier', models.CharField(max_length=32)),
                ('duration', models.IntegerField(help_text='Duration in ms')),
                ('approved', models.BooleanField(default=False)),
                ('queued', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('submitted_by', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='spotify.session')),
            ],
            options={
                'permissions': (('submit_song_request', 'Can submit song requests'), ('approve_song_request', 'Approve song requests')),
            },
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.spotifyuser'),
        ),
    ]
