# Generated by Django 3.1.8 on 2021-10-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_auto_20211014_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepting_requests', models.BooleanField(default=True)),
                ('allow_explicit', models.BooleanField(default=True)),
                ('require_payment', models.BooleanField(default=False)),
                ('auth_token', models.CharField(blank=True, max_length=250, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=250, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event2019')),
            ],
        ),
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('identifier', models.CharField(max_length=32)),
                ('duration', models.IntegerField(help_text='Duration in ms')),
                ('approved', models.BooleanField(default=False)),
                ('queued', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('submitted_by', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='spotify.session')),
            ],
            options={
                'permissions': (('submit_song_request', 'Can submit song requests'), ('approve_song_request', 'Approve song requests')),
            },
        ),
    ]
