# Generated by Django 3.1.13 on 2021-11-04 15:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='application_form',
            field=models.CharField(default='', max_length=128, verbose_name='Link to external application form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='closes',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Applications Close'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.position')),
            ],
        ),
    ]
