# Generated by Django 3.1.13 on 2021-11-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_auto_20211104_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='closes',
            field=models.DateField(blank=True, null=True, verbose_name='Applications Close'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Position Name'),
        ),
    ]
