# Generated by Django 3.1.13 on 2021-11-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_auto_20211111_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'permissions': [('apply', 'Can apply for positions')]},
        ),
    ]
