# Generated by Django 3.1.13 on 2021-11-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0005_auto_20211112_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationInstance',
        ),
    ]
