# Generated by Django 3.1.13 on 2021-11-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0006_delete_applicationinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='application_form',
            field=models.URLField(max_length=128, verbose_name='Link to external application form'),
        ),
        migrations.AlterField(
            model_name='position',
            name='closes',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Applications Close'),
        ),
    ]
