# Generated by Django 3.1.13 on 2021-12-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0007_auto_20211114_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='application_form',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='Link to external application form'),
        ),
    ]
