# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170917_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=500)),
                ('format', models.CharField(choices=[(b'alert', b'Alert'), (b'notification', b'Notification')], max_length=12)),
                ('type', models.CharField(choices=[(b'info', b'Info'), (b'advisory', b'Advisory'), (b'warning', b'Warning')], max_length=8)),
                ('dismissible', models.BooleanField(default=False)),
                ('target', models.CharField(help_text=b"To target a specific page, include the full pathname (i.e. '/services/lighting.html' or '/events/'). To target a directory, include only the directory name (i.e. 'events'). For a sitewide notification, enter 'All'.", max_length=200)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set([('format', 'target')]),
        ),
    ]
