# Generated by Django 3.1.2 on 2020-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='api_key',
            field=models.CharField(max_length=36, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='format',
            field=models.CharField(choices=[('alert', 'Alert'), ('notification', 'Notification')], max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(help_text="To target a specific page, include the full pathname (i.e. '/services/lighting.html' or '/events/'). To target a directory, include only the directory name (i.e. 'events'). For a sitewide notification, enter 'All'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('advisory', 'Advisory'), ('warning', 'Warning')], max_length=8),
        ),
    ]
