# Generated by Django 3.1.8 on 2021-12-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210207_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='endpoints',
        ),
    ]
