# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(help_text='Relative path to endpoint (Ex: http://lnl.wpi.edu/api/v1/example --> example)', max_length=100, verbose_name='Path')),
                ('description', models.TextField(help_text='What is this endpoint used for?')),
                ('parameter_note', models.CharField(blank=True, help_text='Explain any special relationships between parameters here', max_length=500, null=True, verbose_name='Note')),
                ('example', models.CharField(help_text='Provide an example of how the parameters might be formatted. (Ex: id=Example&display=true)', max_length=200)),
                ('response', models.TextField(help_text='Paste the API response using the URL generated from the example above')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS')], max_length=7)),
                ('auth', models.CharField(choices=[('none', 'None'), ('session', 'Session-based'), ('project', 'Project-based')], max_length=7)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='api.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(blank=True, max_length=120, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterOptions', to='api.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('int', 'integer'), ('string', 'string'), ('bool', 'boolean'), ('datetime', 'datetime'), ('date', 'date'), ('time', 'time'), ('array', 'array')], max_length=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestParameter',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Parameter')),
                ('required', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.Endpoint')),
            ],
            options={
                'verbose_name': 'Request Parameter',
            },
            bases=('api.parameter',),
        ),
        migrations.CreateModel(
            name='ResponseKey',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Parameter')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsekeys', to='api.Endpoint')),
            ],
            options={
                'verbose_name': 'Response Value',
            },
            bases=('api.parameter',),
        ),
        migrations.AddField(
            model_name='option',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Parameter'),
        ),
    ]
