# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestparameter',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='responsekey',
            name='endpoint',
        ),
        migrations.AddField(
            model_name='parameter',
            name='endpoint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='api.Endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='method',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=7),
        ),
    ]
