# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200327_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='url',
            field=models.CharField(help_text='Relative path to endpoint (Ex: https://lnl.wpi.edu/api/v1/example --> example)', max_length=100, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.Endpoint'),
        ),
    ]
