# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_endpoint_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('attempts', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='method',
            name='auth',
            field=models.CharField(choices=[('none', 'None'), ('token', 'Token-based'), ('project', 'Project-based')], max_length=7),
        ),
    ]
