# Generated by Django 3.1.14 on 2023-03-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset_display_name', models.CharField(max_length=10)),
                ('asset_desc', models.CharField(blank=True, max_length=32, null=True)),
                ('asset_status', models.CharField(default='UNK', max_length=5)),
                ('asset_position', models.IntegerField(blank=True, null=True)),
                ('asset_archived', models.BooleanField()),
                ('asset_last_seen', models.DateTimeField()),
                ('asset_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=5)),
                ('asset_position', models.IntegerField(blank=True, null=True)),
                ('event_datetime', models.DateTimeField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sats.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
