# Generated by Django 3.1.14 on 2023-04-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_archived',
            field=models.BooleanField(default=False),
        ),
    ]
