# Generated by Django 3.1.14 on 2023-04-25 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sats', '0002_auto_20230425_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
