# Generated by Django 3.1.2 on 2020-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200628_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(help_text='Accepts raw text and/or HTML input'),
        ),
        migrations.AlterField(
            model_name='page',
            name='css',
            field=models.TextField(blank=True, verbose_name='CSS'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, help_text='This page description may appear in search engine results and along with any links to this page.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='noindex',
            field=models.BooleanField(default=False, verbose_name='Hide from search engines'),
        ),
    ]
