# Generated by Django 3.1.6 on 2021-02-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201028_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sitemap',
            field=models.BooleanField(default=False, verbose_name='Include in Sitemap'),
        ),
        migrations.AddField(
            model_name='page',
            name='sitemap_category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
