# Generated by Django 3.1.6 on 2021-02-18 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0005_auto_20210207_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('icon', models.CharField(blank=True, help_text='Icon or image HTML', max_length=300, null=True)),
                ('content', models.TextField()),
                ('inverted', models.BooleanField(default=False, verbose_name='Dark Theme')),
                ('action_title', models.CharField(blank=True, help_text='If left blank this button will not be displayed', max_length=32, null=True, verbose_name='Action Button - Text')),
                ('action_href', models.URLField(blank=True, help_text='URL to go to when clicked. If not supplied button will not be displayed.', max_length=128, null=True, verbose_name='Action Button - href')),
                ('action_color', models.CharField(blank=True, max_length=16, null=True, verbose_name='Action Button - Color')),
                ('new_window', models.BooleanField(default=False, verbose_name='Action Button - Open in New Window')),
                ('next_btn', models.CharField(blank=True, help_text='Defaults to "Next"', max_length=32, null=True, verbose_name='Next Button - Text')),
                ('groups', models.ManyToManyField(blank=True, help_text='Select groups of users to display this to.', to='auth.Group')),
                ('users', models.ManyToManyField(blank=True, help_text='Select users to display this to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screens', models.ManyToManyField(blank=True, related_name='records', to='pages.OnboardingScreen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
