# Generated by Django 2.1.2 on 2018-10-22 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0002_Permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitinstance',
            name='pit_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pitinstances', to='projection.PITLevel'),
        ),
    ]
