# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0004_auto_20200208_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitinstance',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
