# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-28 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0005_auto_20200210_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pitrequest', to='projection.PITLevel')),
                ('projectionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitrequest', to='projection.Projectionist')),
            ],
        ),
    ]
