# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0006_pitrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitinstance',
            name='created_on',
            field=models.DateField(),
        ),
    ]
