# Generated by Django 3.1.14 on 2022-10-23 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_eeprom_id', models.CharField(max_length=32, verbose_name='Key EEPROM ID')),
                ('pretty_name', models.CharField(max_length=32, verbose_name='Display Name')),
            ],
        ),
        migrations.CreateModel(
            name='KeyAuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Time Logged')),
                ('card_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='HID Card ID')),
                ('event_type', models.CharField(max_length=16, verbose_name='Audit Type')),
                ('misc_text', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('key_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='hacka.key', verbose_name='Key')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='key_audit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
