# Generated by Django 3.1.2 on 2020-10-28 18:05

import accounts.models
import data.storage
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Officer Position')),
                ('wpibox', models.IntegerField(blank=True, null=True, verbose_name='WPI Box Number')),
                ('phone', models.CharField(blank=True, max_length=24, null=True, verbose_name='Phone Number')),
                ('carrier', models.CharField(blank=True, choices=[('', 'Opt-out'), ('vtext.com', 'Verizon'), ('txt.att.net', 'AT&T'), ('myboostmobile.com', 'Boost Mobile'), ('mms.cricketwireless.net', 'Cricket'), ('msg.fi.google.com', 'Google Fi'), ('mymetropcs.com', 'Metro PCS'), ('mmst5.tracfone.com', 'Simple Mobile'), ('messaging.sprintpcs.com', 'Sprint'), ('tmomail.net', 'T-Mobile'), ('vmobl.com', 'Virgin Mobile'), ('vmobile.ca', 'Virgin Mobile Canada'), ('vtext.com', 'Xfinity Mobile')], default='', help_text='By selecting your cellular carrier you consent to receiving text messages from LNL', max_length=25, null=True, verbose_name='Cellular Carrier')),
                ('addr', models.TextField(blank=True, null=True, verbose_name='Address / Office Location')),
                ('mdc', models.CharField(blank=True, max_length=32, null=True, verbose_name='MDC')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='Nickname')),
                ('student_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Student ID')),
                ('class_year', models.PositiveIntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('away_exp', models.DateField(blank=True, null=True, verbose_name='Away Status Expiration')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'class_year'),
                'permissions': (('change_group', 'Change the group membership of a user'), ('edit_mdc', 'Change the MDC of a user'), ('view_member', 'View LNL members')),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OfficerImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=data.storage.OverwriteStorage(), upload_to=accounts.models.path_and_rename, verbose_name='Image')),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='img', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
