# Generated by Django 3.1.8 on 2021-10-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name', 'first_name', 'class_year'), 'permissions': (('change_membership', 'Change the group membership of a user'), ('edit_mdc', 'Change the MDC of a user'), ('view_member', 'View LNL members'))},
        ),
    ]
