# Generated by Django 3.1.8 on 2022-01-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingtype_archived'),
        ('accounts', '0007_comm_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='meeting_invite_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='invite_subscriptions', to='meetings.MeetingType'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='meeting_invites',
            field=models.BooleanField(default=False, help_text='Opt-in to receiving calendar invites for meetings'),
        ),
    ]
