# Generated by Django 3.1.14 on 2023-03-28 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_officer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1962), django.core.validators.MaxValueValidator(2029)]),
        ),
    ]
