# Generated by Django 3.1.14 on 2022-10-23 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_officer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hid_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='HID Swipe ID'),
        ),
    ]
