# Generated by Django 3.1.14 on 2023-08-27 17:51

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_officer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1962), django.core.validators.MaxValueValidator(2029)]),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='event_edited_field_subscriptions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('event_name', 'Event name'), ('description', 'Description'), ('location', 'Location'), ('contact', 'Contact'), ('lnl_contact', 'LNL contact'), ('billing_org', 'Billing org'), ('datetime_setup_complete', 'Datetime setup complete'), ('datetime_start', 'Datetime start'), ('datetime_end', 'Datetime end'), ('internal_notes', 'Internal notes'), ('billed_in_bulk', 'Billed in bulk'), ('org', 'Client')], default=['location', 'datetime_setup_complete', 'datetime_start', 'datetime_end'], max_length=149),
        ),
    ]
