# Generated by Django 3.1.14 on 2023-03-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230328_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_badge_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Current Badge ID'),
        ),
    ]
