# Generated by Django 3.1.14 on 2023-09-05 20:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230827_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='event_edited_field_subscriptions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('event_name', 'Event name'), ('event_status', 'Status'), ('description', 'Description'), ('location', 'Location'), ('contact', 'Contact'), ('lnl_contact', 'LNL contact'), ('billing_org', 'Billing org'), ('datetime_setup_complete', 'Datetime setup complete'), ('datetime_start', 'Datetime start'), ('datetime_end', 'Datetime end'), ('internal_notes', 'Internal notes'), ('billed_in_bulk', 'Billed in bulk'), ('org', 'Client')], default=['location', 'datetime_setup_complete', 'datetime_start', 'datetime_end'], max_length=162),
        ),
    ]
