# Generated by Django 3.1.3 on 2024-07-31 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230905_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1962), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
