# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181122_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='away_exp',
            field=models.DateField(blank=True, null=True, verbose_name=b'Away Status Expiration'),
        ),
    ]
