# Generated by Django 4.2.13 on 2026-02-25 04:52

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userpreferences_cc_add_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superuser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='class_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1962), django.core.validators.MaxValueValidator(2032)]),
        ),
    ]
