# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-02 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_away_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carrier',
            field=models.CharField(blank=True, choices=[(b'', b'Opt-out'), (b'vtext.com', b'Verizon'), (b'txt.att.net', b'AT&T'), (b'myboostmobile.com', b'Boost Mobile'), (b'mms.cricketwireless.net', b'Cricket'), (b'msg.fi.google.com', b'Google Fi'), (b'mymetropcs.com', b'Metro PCS'), (b'mmst5.tracfone.com', b'Simple Mobile'), (b'messaging.sprintpcs.com', b'Sprint'), (b'tmomail.net', b'T-Mobile'), (b'vmobl.com', b'Virgin Mobile'), (b'vmobile.ca', b'Virgin Mobile Canada'), (b'vtext.com', b'Xfinity Mobile')], default=b'', help_text=b'By selecting your cellular carrier you consent to receiving text messages from LNL', max_length=25, null=True, verbose_name=b'Cellular Carrier'),
        ),
    ]
