# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-06 04:52
from __future__ import unicode_literals

import accounts.models
import data.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200327_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=data.storage.OverwriteStorage(), upload_to=accounts.models.path_and_rename, verbose_name=b'Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AddField(
            model_name='officerimg',
            name='officer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='img', to=settings.AUTH_USER_MODEL),
        ),
    ]
