# Generated by Django 3.1.8 on 2021-11-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
