# Generated by Django 2.0.9 on 2018-10-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20181021_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccnoticesend',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='meetingccnoticeevents', to='events.BaseEvent'),
        ),
        migrations.AlterField(
            model_name='meetingannounce',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='meetingannouncements', to='events.BaseEvent'),
        ),
    ]
