# Generated by Django 2.0.9 on 2018-10-28 22:31

from django.db import migrations, models
from django.db.migrations.operations.models import Operation

class CopyFieldsBetweenTables(Operation):

    reversible = False

    def __init__(self, model_from_name, model_to_name, columns):
        self.model_from_name = model_from_name
        self.model_to_name = model_to_name
        self.columns_from, self.columns_to = zip(*columns)

    def state_forwards(self, app_label, state):
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        columns_to = ", ".join(('`%s`' % col for col in self.columns_to))
        columns_from = ", ".join(('`%s`' % col for col in self.columns_from))
        base_query = 'INSERT INTO %s_%s (%s) SELECT %s FROM %s_%s;' % (
            app_label, self.model_to_name, columns_to, columns_from, app_label, self.model_from_name
        )
        schema_editor.execute(base_query)

    def describe(self):
        return "Copies between two tables for %s" % self.name

class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20181021_2135'),
    ]

    database_operations = [
        migrations.CreateModel(
            name='ccnoticesend_events_temp',
            fields=[
                ('ccnoticesend_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
            ]
        ),
        CopyFieldsBetweenTables(
            model_from_name='ccnoticesend_events',
            model_to_name='ccnoticesend_events_temp',
            columns=[('ccnoticesend_id', 'ccnoticesend_id'), ('event_id', 'event_id')],
        ),
        migrations.RemoveField(
            model_name='ccnoticesend',
            name='events',
        ),
        # ---------------------
        migrations.CreateModel(
            name='meetingannounce_events_temp',
            fields=[
                ('meetingannounce_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
            ]
        ),
        CopyFieldsBetweenTables(
            model_from_name='meetingannounce_events',
            model_to_name='meetingannounce_events_temp',
            columns=[('meetingannounce_id', 'meetingannounce_id'), ('event_id', 'event_id')],
        ),
        migrations.RemoveField(
            model_name='meetingannounce',
            name='events',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=[]
        ),
    ]
