# Generated by Django 2.0.9 on 2018-10-28 22:31

from django.db import migrations, models
from django.db.migrations.operations.models import Operation

class CopyFieldsBetweenTables(Operation):

    reversible = False

    def __init__(self, model_from_name, model_to_name, columns):
        self.model_from_name = model_from_name
        self.model_to_name = model_to_name
        self.columns_from, self.columns_to = zip(*columns)

    def state_forwards(self, app_label, state):
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        columns_to = ", ".join(('`%s`' % col for col in self.columns_to))
        columns_from = ", ".join(('`%s`' % col for col in self.columns_from))
        base_query = 'INSERT INTO %s_%s (%s) SELECT %s FROM %s_%s;' % (
            app_label, self.model_to_name, columns_to, columns_from, app_label, self.model_from_name
        )
        schema_editor.execute(base_query)

    def describe(self):
        return "Copies between two tables for %s" % self.name

class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_Event2019_1'),
        ('events', '0021_Event2019'),
    ]
    
    database_operations = [
        migrations.AddField(
            model_name='ccnoticesend',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='meetingccnoticeevents', to='events.BaseEvent'),
        ),
        CopyFieldsBetweenTables(
            model_from_name='ccnoticesend_events_temp',
            model_to_name='ccnoticesend_events',
            columns=[('ccnoticesend_id', 'ccnoticesend_id'), ('event_id', 'baseevent_id')],
        ),
        migrations.RunSQL('DROP TABLE meetings_ccnoticesend_events_temp;'),
        # ---------------------
        migrations.AddField(
            model_name='meetingannounce',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='meetingannouncements', to='events.BaseEvent'),
        ),
        CopyFieldsBetweenTables(
            model_from_name='meetingannounce_events_temp',
            model_to_name='meetingannounce_events',
            columns=[('meetingannounce_id', 'meetingannounce_id'), ('event_id', 'baseevent_id')],
        ),
        migrations.RunSQL('DROP TABLE meetings_meetingannounce_events_temp;'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='ccnoticesend',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='meetingccnoticeevents', to='events.BaseEvent'),
        ),
        migrations.AlterField(
            model_name='meetingannounce',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='meetingannouncements', to='events.BaseEvent'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        ),
    ]
