# Generated by Django 4.2.13 on 2025-01-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0002_reportedmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "permissions": (),
            },
        ),
    ]
