# Generated by Django 4.2.13 on 2025-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0003_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="channel_id",
        ),
        migrations.AlterField(
            model_name="channel",
            name="id",
            field=models.CharField(
                max_length=256, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
