# Generated by Django 3.1.8 on 2022-01-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRecord',
        ),
    ]
