# Generated by Django 2.1.2 on 2018-10-22 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_unicode_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text="If this is a subcategory, the parent is what this is a subcategory of. Choose '---' if not.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.EquipmentCategory'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='usual_place',
            field=models.ForeignKey(blank=True, help_text='Default place for items of this category. Inherits from parent categories.', null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Location'),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='home',
            field=models.ForeignKey(blank=True, help_text='Place where this item typically resides.', null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Location'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintentry',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.EquipmentStatus'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
