# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-15 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0037_event2019_max_crew'),
        ('inventory', '0010_auto_20181021_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=120)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='events.Location')),
                ('users', models.ManyToManyField(related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_access_logs', 'View Access Logs'),),
            },
        ),
    ]
