# Generated by Django 3.1.2 on 2020-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0003_auto_20200208_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ['old_path'], 'verbose_name': 'redirect', 'verbose_name_plural': 'redirects'},
        ),
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(blank=True, help_text='This can be either an absolute path (as above) or a full URL starting with “http://”.', max_length=200, verbose_name='redirect to'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(db_index=True, help_text='This should be an absolute path, excluding the domain name. Example: “/events/search/”.', max_length=200, verbose_name='redirect from'),
        ),
    ]
