# Generated by Django 4.2.13 on 2024-12-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0004_auto_20201028_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(blank=True, help_text='This can be either an absolute path (as above) or a full URL starting with a scheme such as “https://”.', max_length=200, verbose_name='redirect to'),
        ),
    ]
