# Generated by Django 3.1.2 on 2020-10-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200628_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date', '-recorded_on']},
        ),
    ]
